import type { Metadata } from "next";
import "./globals.css";
// Supports weights 100-900
import "@fontsource-variable/jost";
// Supports weights 200-800
import "@fontsource-variable/manrope";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
